apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mega-coder.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mega-coder.name" . }}
type: Opaque
stringData:
  APP_SHARED_SECRET: {{ .Values.secrets.appSharedSecret | quote }}
