apiVersion: v1
kind: Service
metadata:
  name: {{ include "mega-coder.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: {{ include "mega-coder.name" . }}
spec:
  type: {{ .Values.service.webType | default .Values.service.type }}
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: {{ include "mega-coder.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: http
      {{- if eq (.Values.service.webType | default .Values.service.type) "NodePort" }}
      nodePort: {{ .Values.service.webNodePort }}
      {{- end }}
